### PR TITLE
python module

### PR DESCRIPTION
**Pull request by scarrazza**
Here we implement the python module for PineAPPL, todo list:
- [x] installation system
- [x] use a python like API
- [x] sphinx documentation
- [x] integration with python examples
- [x] implement tests during github action

### CODE REVIEW

**Comment by scarrazza** [comment]
@cschwan please let me know if you prefer to extend the `rules.yml` or create a new workflow for testing this module.

**Comment by cschwan** [comment]
Create a new workflow `python.yaml`!

**Comment by scarrazza** [comment]
Indeed, thanks. Concerning the python API, do you think we should keep or drop the keyval object allocation?

**Comment by scarrazza** [comment]
Other question, do you know the prefix where the pc file is installed? 
(I just tried in `/home/runner/prefix/lib/pkgconfig` without success)

**Comment by cschwan** [comment]
What would you have instead of a keyval object?

I've installed everying under `/home/runner/prefix`, see here

https://github.com/N3PDF/pineappl/blob/f8bbcf45661827cf338cc91686531eb6259da90f/.github/workflows/rust.yml#L32

**Comment by scarrazza** [comment]
> What would you have instead of a keyval object?

I can create this object directly in the `grid.__init__` method, instead of passing as argument.

**Comment by cschwan** [comment]
> > What would you have instead of a keyval object?
> 
> I can create this object directly in the `grid.__init__` method, instead of passing as argument.

Sure! Have a look at the following to see what values are currently supported:

https://github.com/N3PDF/pineappl/blob/f8bbcf45661827cf338cc91686531eb6259da90f/pineappl_capi/src/lib.rs#L285-L323

**Comment by cschwan** [comment]
@scarrazza You can't use export, instead you have to use `echo` in the way I've shown you above.

**Comment by scarrazza** [comment]
> You can't use export, instead you have to use echo in the way I've shown you above.

That's not true, the export is working fine see [here](https://github.com/N3PDF/pineappl/runs/971317026#step:12:4).

From this log the `pineappl.rc` is not stored there, I can only see the `lhapdf.pc` in `/home/runner/prefix/lib/pkgconfig`.
Do you understand why the `pineappl.rc` is not copied to the right direction?

**Comment by cschwan** [comment]
Because I didn't install it ...

**Comment by scarrazza** [comment]
Ok, could you please add these changes to the rust.yml in this PR?

**Comment by cschwan** [comment]
Numpy is apparently missing.

**Comment by cschwan** [comment]
Is anything missing or can I merge it?

**Comment by scarrazza** [comment]
Yes, I think this is now completed. 
The next steps are summarized in #33 and #34 .

**Pull request merged**
