### PR TITLE
adding example in python

### PR DESCRIPTION
**Pull request by scarrazza**
This PR implements a simple example in python.

### CODE REVIEW

**Comment by scarrazza** [comment]
In principle we could create a python module with the C interface instead of distributing the `pineappl.py`.

**Comment by cschwan** [comment]
- Can you complete the example so that it also, like the C example, performs the convolution?
- We could make the Python interface a little more Python-like, for example by stripping `pineappl` from every name (that's the module name already), and also strip `lumi`, `keyval`, and `grid` from the name of the functions (they should be members for the respective classes, instead of taking it as the first argument). The `pineappl_{lumi,keyval,grid}_new` functions should be constructors.
- Is it possible to make the `_delete` functions destructors that are automatically called when the objects go out of scope?

**Comment by cschwan** [comment]
> In principle we could create a python module with the C interface instead of distributing the `pineappl.py`.

Sounds like a good idea.

**Comment by cschwan** [comment]
This might be interesting: https://crates.io/crates/pyo3

**Comment by scarrazza** [comment]
Thanks for the comments, I will open another PR with the python module implementation.
If you prefer we can merge this now.

**Pull request merged**
